FROM python:3.7-alpine

COPY ./requirements.txt .


RUN \
    apk update && \
    apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev openssl-dev libffi-dev g++ build-base linux-headers postgresql-dev postgresql-contrib pcre-dev bash alpine-sdk libpq libjpeg-turbo libstdc++ && \
    pip install wheel && \
    pip install -r requirements.txt && \
    apk del .build-deps
