# Docker compose to build image.

version: "3"
services:
  base:
    image: "fampay:base"
    build:
      context: .
      dockerfile: Dockerfile-base
  web:
    ports:
      - 8000:8000
    links:
      - postgres
      - redis
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && export DJANGO_SETTINGS_MODULE=assignment.settings && gunicorn assignment.wsgi:application -b 0.0.0.0:8000 -w 1 --log-level info --keep-alive 200"
    build:
      context: .
      dockerfile: Dockerfile
  postgres:
      image: postgres:latest
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=fampay
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A assignment worker -l info
    volumes:
      - .:/src
    env_file: .env
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A assignment beat -l info
    env_file: .env
    volumes:
      - .:/src
    depends_on:
      - redis
      - web